language: swift
osx_image: xcode10.2

install:
  - brew install swiftlint

script:
  - xcodebuild -scheme Example -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8,OS=latest' build test
  - swiftlint --strict

after_success:
  - bash <(curl -s https://codecov.io/bash)
